import { describe, expect, it } from "vitest";
import { MORE_NAV, NAV_ITEMS, PRIMARY_NAV } from "./nav";
import { EXPLICIT_ROUTE_PATHS, SECTION_PAGES } from "./router";

describe("nav", () => {
  it("chat is home", () => {
    expect(NAV_ITEMS.find((i) => i.to === "/")?.label).toBe("Chat");
    expect(NAV_ITEMS.some((i) => i.to === "/dashboard")).toBe(true);
  });

  it("primary + more partition every item exactly once", () => {
    const more = MORE_NAV.flatMap((g) => g.items);
    expect(PRIMARY_NAV.length + more.length).toBe(NAV_ITEMS.length);
    expect(PRIMARY_NAV.some((i) => more.includes(i))).toBe(false);
    expect(new Set(NAV_ITEMS.map((i) => i.to)).size).toBe(NAV_ITEMS.length);
  });

  // Routes are generated by intersecting NAV_ITEMS with SECTION_PAGES, so drift
  // either way is silent: a nav entry with no page renders a dead link, and a
  // page with no nav entry never gets a route and 404s when typed.
  it("every nav path has a page and every page has a nav path", () => {
    const navPaths = NAV_ITEMS.map((i) => i.to);
    const routedPaths = [...EXPLICIT_ROUTE_PATHS, ...Object.keys(SECTION_PAGES)];
    expect(navPaths.filter((p) => !routedPaths.includes(p))).toEqual([]);
    expect(routedPaths.filter((p) => !navPaths.includes(p))).toEqual([]);
  });
});
