// AUTO-GENERATED by scripts/generate-events.mjs from contract/events.json.
// Do not edit — re-sync via scripts/sync-contract.sh + npm run generate:events.
// Sources of truth: agos ws/protocol.rs frame TAGS + kernel SUBSCRIBABLE_EVENTS.

export const CLIENT_FRAME_TAGS = ["subscribe", "unsubscribe", "chat.send", "notification.respond", "chat.cancel", "task.cancel", "ping"] as const;
export const SERVER_FRAME_TAGS = ["subscribed", "unsubscribed", "event", "chat.chunk", "chat.done", "chat.cancelled", "error", "pong"] as const;
export type ClientFrameTag = (typeof CLIENT_FRAME_TAGS)[number];
export type ServerFrameTag = (typeof SERVER_FRAME_TAGS)[number];

export interface GeneratedEventCategory {
  /** PascalCase category name (matches the kernel EventCategory variant). */
  value: string;
  /** Bare permission resource required to observe the category. */
  resource: string;
  /** Parser-accepted event type names in this category. */
  events: readonly string[];
}

export const EVENT_CATALOG_GEN: readonly GeneratedEventCategory[] = [
  { value: "AgentLifecycle", resource: "events.agent_lifecycle", events: ["AgentAdded", "AgentRemoved", "AgentPermissionGranted", "AgentPermissionRevoked"] },
  { value: "TaskLifecycle", resource: "events.task_lifecycle", events: ["TaskStarted", "TaskCompleted", "TaskFailed", "TaskTimedOut", "TaskDelegated", "TaskRetrying", "TaskDeadlockDetected", "TaskPreempted"] },
  { value: "SecurityEvents", resource: "events.security", events: ["PromptInjectionAttempt", "CapabilityViolation", "UnauthorizedToolAccess", "SecretsAccessAttempt", "SandboxEscapeAttempt", "AuditLogTamperAttempt", "AgentImpersonationAttempt", "UnverifiedToolInstalled"] },
  { value: "MemoryEvents", resource: "events.memory", events: ["ContextWindowNearLimit", "ContextWindowExhausted", "EpisodicMemoryWritten", "SemanticMemoryConflict", "MemorySearchFailed", "WorkingMemoryEviction"] },
  { value: "SystemHealth", resource: "events.system_health", events: ["CPUSpikeDetected", "MemoryPressure", "DiskSpaceLow", "DiskSpaceCritical", "ProcessCrashed", "NetworkInterfaceDown", "ContainerResourceQuotaExceeded", "KernelSubsystemError"] },
  { value: "HardwareEvents", resource: "events.hardware", events: ["GPUAvailable", "GPUMemoryPressure", "SensorReadingThresholdExceeded", "DeviceConnected", "DeviceDisconnected", "HardwareAccessGranted", "DeviceMounted", "DeviceUnmounted", "DeviceEjected", "PrintJobSubmitted", "PrintJobCancelled", "AudioCaptureStarted", "AudioCaptureStopped", "AudioPlaybackStarted", "WebcamCaptureStarted", "WebcamCaptureStopped", "BluetoothScanStarted", "BluetoothPairRequested", "BluetoothConnected"] },
  { value: "ToolEvents", resource: "events.tool", events: ["ToolInstalled", "ToolRemoved", "ToolExecutionFailed", "ToolSandboxViolation", "ToolResourceQuotaExceeded", "ToolChecksumMismatch", "ToolRegistryUpdated"] },
  { value: "AgentCommunication", resource: "events.agent_communication", events: ["DirectMessageReceived", "BroadcastReceived", "DelegationReceived", "DelegationResponseReceived", "MessageDeliveryFailed", "AgentUnreachable"] },
  { value: "ScheduleEvents", resource: "events.schedule", events: ["CronJobFired", "ScheduledTaskMissed", "ScheduledTaskCompleted", "ScheduledTaskFailed"] },
  { value: "ExternalEvents", resource: "events.external", events: ["WebhookReceived", "ExternalFileChanged", "ExternalAPIEvent", "ExternalAlertReceived"] },
];
