// Generate src/realtime/events.gen.ts from contract/events.json.
//
// contract/events.json is produced by the agos `gen-events` bin (synced by
// scripts/sync-contract.sh) from the Rust sources of truth: the WS frame TAGS
// in ws/protocol.rs and the kernel's SUBSCRIBABLE_EVENTS table.
import { readFileSync, writeFileSync } from "node:fs";

const src = JSON.parse(readFileSync(new URL("../contract/events.json", import.meta.url), "utf8"));
const lit = (arr) => arr.map((s) => JSON.stringify(s)).join(", ");

const out = `// AUTO-GENERATED by scripts/generate-events.mjs from contract/events.json.
// Do not edit — re-sync via scripts/sync-contract.sh + npm run generate:events.
// Sources of truth: agos ws/protocol.rs frame TAGS + kernel SUBSCRIBABLE_EVENTS.

export const CLIENT_FRAME_TAGS = [${lit(src.clientFrames)}] as const;
export const SERVER_FRAME_TAGS = [${lit(src.serverFrames)}] as const;
export type ClientFrameTag = (typeof CLIENT_FRAME_TAGS)[number];
export type ServerFrameTag = (typeof SERVER_FRAME_TAGS)[number];

export interface GeneratedEventCategory {
  /** PascalCase category name (matches the kernel EventCategory variant). */
  value: string;
  /** Bare permission resource required to observe the category. */
  resource: string;
  /** Parser-accepted event type names in this category. */
  events: readonly string[];
}

export const EVENT_CATALOG_GEN: readonly GeneratedEventCategory[] = [
${src.catalog
  .map(
    (c) =>
      `  { value: ${JSON.stringify(c.value)}, resource: ${JSON.stringify(c.resource)}, events: [${lit(c.events)}] },`,
  )
  .join("\n")}
];
`;

writeFileSync(new URL("../src/realtime/events.gen.ts", import.meta.url), out);
console.log("wrote src/realtime/events.gen.ts");
